name: tests

on: push

jobs:
  test:
    name: run tests
    runs-on: ubuntu-20.04

    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd ./.github
          docker compose build ruby
      - name: tests
        run: |
          cd ./.github
          docker compose run --rm ruby ./tests.sh
